#=========================================================================
# Constraints
#=========================================================================

name: constraints

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - constraints.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: undefined
  design_name: undefined

commands: 
  - cat constraints.tcl > outputs/constraints.tcl
