#=========================================================================
# Custom Scripts -- cadence-innovus-flowstep
#=========================================================================

name: custom-flowstep

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - setup.tcl

