name: rtl

outputs:
  - design.v
  - design.vcs.v
  - design.sdc

commands:
  - sed -i '/parameter/d' clock_generator.v
  - sed -i 's/nand/sky130_fd_sc_hd__nand/g' clock_generator.v
  - sed -i 's/dfxbp/sky130_fd_sc_hd__dfxbp/g' clock_generator.v
  - sed -i 's/mux/sky130_fd_sc_hd__mux/g' clock_generator.v
  - sed -i 's/clkdly/sky130_fd_sc_hd__clkdly/g' clock_generator.v
  - sed -i 's/clkinv/sky130_fd_sc_hd__clkinv/g' clock_generator.v
  - sed -i 's/clkbuf/sky130_fd_sc_hd__clkbuf/g' clock_generator.v
  - sed -i '/#(/,+6d' clock_generator.v
  - cat clock_generator.v > outputs/design.v 
  - cat outputs/design.v > outputs/design.vcs.v 
  - cat clock_generator.sdc > outputs/design.sdc
